# Generated by Django 2.0.7 on 2018-07-14 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0006_auto_20180714_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswa',
            name='gender',
        ),
    ]
