# Generated by Django 2.0.7 on 2018-07-14 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0007_remove_mahasiswa_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswa',
            name='Gender',
        ),
    ]
