# Generated by Django 2.0.7 on 2018-07-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0008_remove_mahasiswa_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='gender',
            field=models.CharField(choices=[('PR', 'Pria'), ('PR', 'Wanita')], default='PR', max_length=2),
        ),
    ]
