# Generated by Django 2.0.7 on 2018-07-14 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0010_auto_20180714_0344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mahasiswa',
        ),
    ]
