# Generated by Django 2.0.7 on 2018-07-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0012_mahasiswa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='jenis_kelamin',
            field=models.CharField(choices=[('PR', 'Pria'), ('WN', 'Wanita')], default='PR', max_length=2),
        ),
    ]
